sudo: false
language: python

python:
  # Uses Python3 memoryview type.
  # - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy

matrix:
  # include test for flake8
  include:
    - python: 3.5
      script: tox -e flake8

install:
  - pip install tox
  - pip install --install-option="--no-cython-compile" https://github.com/cython/cython/archive/a56ee0711ef0bcd338d9f9773b6609210f05946b.zip

script:
  - tox -e py
