sudo: false
language: python

python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy

matrix:
  # include test for flake8
  include:
    - python: 3.5
      script: tox -e flake8

install:
  - pip install tox
  - pip install --install-option="--no-cython-compile" https://github.com/cython/cython/archive/a0f44623091d4da88e811ccde804693e3519583e.zip

script:
  - tox -e py
