sudo: false
language: python

python:
  # Uses Python3 memoryview type.
  # - 2.6
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - pypy

matrix:
  # include test for flake8
  include:
    - python: 3.5
      script: tox -e flake8

install:
  - pip install tox
  - pip install --install-option="--no-cython-compile" https://github.com/cython/cython/archive/8f586aa97bcbb8c10d7ee34ff858d69329b0c4af.zip

script:
  - tox -e py
